# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('directions', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('recipe_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media')),
                ('ingredients', models.ManyToManyField(to='main.Ingredients')),
            ],
        ),
    ]
